### ISSUE TITLE
Resolve version conflicts

### ISSUE THREAD

**Issue by Nudin** [konstin/github-wikidata-bot#28]
I saw now several times, that some items don't receive any updates anymore. Example: [yarn](https://www.wikidata.org/wiki/Q28975591). I don't see any reason for this.

Can you look into the logs? Or even better make the bots logs accessible?

**Comment by konstin** [comment]
For yarn, It  should be because there are more than a hundred releases and the bot has a hard limit on 100 releases.

Publishing the logs would be nice, but is difficult because I'm not aware of any easy-to-use services and because the log has grown to 45MB for the main log.

**Comment by Nudin** [comment]
You're right. I always overread the revering of the versions in the code – therefore I thought we're importing always the newest 100 version but in fact we're importing the oldest 100 versions only. That's not really what we want in my opinion since we always want to have the newest version in Wikidata.

I created a PR (#29) to change that. I'm aware that this partly disables the the limit since we will by time import all the new versions without a limit – but it still limits how far we go back in the time on the first import. In general I think the limit is not really important, since this seems to be the only bot limiting the number of it's claims. Other bots import tens of thousands of values for single items. And a few hundred values works still well. I therefore thought about removing the limit completely. On the other side maybe it's still not to bad to have it – there's probably some project out there releasing a nightly release marked as stable every day since years and has therefore pilled up thousands of revisions…

**Comment by konstin** [comment]
I like the idea of using the latest hundred releases. I'm also not strictly opposed to removing the limit, but for now I don't see any incentive to do so.

For validation I've written a query showing the current leaders in terms of number of releases, and found that the current top position is firefox with 455 releases (which are actually human edits, since firefox is not on github):

```
SELECT ?software ?softwareLabel (COUNT(DISTINCT ?release) as ?count)
WHERE {
    ?software p:P348 ?release. # p instead of wdt because we need to ignore the rank but also don't need the actual value
  
  SERVICE wikibase:label { bd:serviceParam wikibase:language "[AUTO_LANGUAGE],en". }
}
GROUP BY ?software  ?softwareLabel
ORDER BY DESC(?count)
```

I'd really like to merge the PR, but unfortunately it seems to have a merge conflict.

**Comment by konstin** [comment]
It's just set to `@daily`. [The stats](https://www.wikidata.org/w/index.php?title=Special:Contributions/Github-wiki-bot&offset=&limit=500&target=Github-wiki-bot) say this translates to 22:00, but doesn't mention the timezone.

**Comment by Nudin** [comment]
Have you deployed the PR #29? Yarn is still not getting any updates.

**Comment by konstin** [comment]
I'm sorry for the misleading comment above; Yarn actually hasn't actually hit the limit but chocked on a duplicate release, https://github.com/yarnpkg/yarn/releases/tag/v1.1.0 and https://github.com/yarnpkg/yarn/releases/tag/v1.1.0-exp.2, which is [checked for in the code](https://github.com/konstin/github-wikidata-bot/blob/c5f11e8632c4567d0d2dbb7dd71f51690b4c8d53/main.py#L409-L412). A logic for resolving such cases (finding out with versions conflict, giving precedence for exact tag matches and skipping conflicting versions when they already have a claim) would IMO be a nice-to-have. 

Since the error log is actually small enough, I've used [gist](https://github.com/defunkt/gist) to upload the error log to https://gist.github.com/konstin/9b90ae895ad9a270102415474a56e613 after each successful run. With 5c730a15961ac5661e70c5d4c0244f3e5eb98703 the duplication errors should also show up in that gist.

**Comment by Nudin** [comment]
Thanks. Will look into it once I find time. The logs are very usefull, I started extracting todo-lists from it and working them.

**Comment by konstin** [comment]
I was actually just using the autoformatter in pycharm, which is afaik pretty close to PEP8 except for ignoring the 80 characters limit. I've changed the code style to [black](https://github.com/ambv/black) since I prefer it's styling over autopep8 and it's becoming quite popular in python world. The only drawback is that it requires python 3.6 to run.

**Comment by Nudin** [comment]
I'll have a close look at the syntax. And give black a try again (had so problems with it in the past).

Back to the conflicts: I plant to fix this, but first wait for the new logs to have a better view of when this actually happens.

**Comment by Nudin** [comment]
With the new logs I could look into the occurrences of duplicate versions. Most of them were caused by the version-regex being not precise enough on detecting the versions. So instead adding a heuristic to decide which to use, I improved the version-detection.
This was my first attempt: https://github.com/konstin/github-wikidata-bot/compare/master...Nudin:master

This works quite well but I there are still special cases the regex does wrong. Also we need a more carefully crafted regex when we want to expand the bot to also handle tags not done with githubs release-functionality. So I wrote a function as well as a pytest testfile with a complex heuristic that get's all test-strings I threw at it right: #32

It's not pretty but seems quite stable and is still very fast (60ns). Can you look at it and try to come up with edge cases I missed?
