### ISSUE TITLE
Use human-readable page rather than github API url as reference

### ISSUE THREAD

**Issue by waldyrious** [konstin/github-wikidata-bot#3]
The GitHub API links that are currently added ([example](https://api.github.com/repos/twbs/bootstrap/releases)) not only are not very user-friendly, but also do not contain all the releases if the list is too long, so they will actually be incorrect for older releases.

A better approach would be to link directly to the corresponding github page for the tag. As an example, [here's a tag with release notes attached](https://github.com/google/code-prettify/releases/tag/2013-03-04), and [a tag without release notes](https://github.com/google/code-prettify/releases/tag/2013-06-21), from the same project.

Note how both use the same link structure (`https://github.com/<USER>/<PROJECT>/releases/tag/<TAG-NAME>`), which makes things easier for the bot :)

**Comment by Nudin** [comment]
This got more important in the last months since version-numbers and there sources from Wikidata get uses more and more in Wikipedia. This results into URLs pointing to the api-endpoint occurring in more and more Wikipedia-Articles. I therefore implemented a fix for this. I also added a release date and a title for the same reason: making references in Wikipedia complete, pretty and human readable.
See the PR for progress and open discussions.

**Comment by konstin** [comment]
This has been fixed in #16
