### ISSUE TITLE
Regression: Mame

### ISSUE THREAD

**Issue by konstin** [konstin/github-wikidata-bot#33]
[Mame](https://github.com/mamedev/mame/releases) skips the dot in the tags (e.g. `mame0199`) and therefore produces extracts incorrect releases. The best solution is probably to check consistency between tag and tag name.

**Comment by konstin** [comment]
Fixed in #34

**Comment by Nudin** [comment]
This case should have not occurred, and only did due to a simple bug in one of the regexps. It's fixed now and the wrong imports for mame have been reverted.
Nevertheless we should think about additional actions to make similar problems less likely:

- [ ] Disallow version numbers starting with leading '0' (0199 in this example)
- [ ] Check if tag-name and release-name yield two different version-numbers and then cancel?

**Comment by konstin** [comment]
I'd go for the second option; The first only works with pre-1.0 releases and there are likely real versions with leading zeros.
